### ISSUE TITLE
Problem after update to 0.21 version

### ISSUE THREAD

**Issue by PepeJoseHU** [guaix-ucm/pyemir#148]
Hello, I meet a problem. After I update pyemir from 0.20 to 0.21, a problem appear when run the pipeline to get image. Error as below:
Traceback (most recent call last):
  File "/home/youdong/Software/anaconda2/envs/emir/bin/numina", line 11, in <module>
    sys.exit(main())
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/cli.py", line 154, in main
    args.command(args, extra_args)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/clirun.py", line 122, in mode_run_obsmode
    mode_run_common(args, extra_args, mode='obs')
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/clirundal.py", line 27, in mode_run_common
    return mode_run_common_obs(args, extra_args)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/clirundal.py", line 51, in mode_run_common_obs
    run_reduce(
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/baserun.py", line 64, in run_reduce
    return run_task_reduce(task, datastore)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/user/baserun.py", line 122, in run_task_reduce
    obsres = datastore.backend.obsres_from_oblock_id(
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/dal/dictdal.py", line 156, in obsres_from_oblock_id
    return self.obsres_from_oblock(oblock, as_mode)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/dal/dictdal.py", line 192, in obsres_from_oblock
    obsres.configuration = self.assembly_instrument(key, date_obs, keyname)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/dal/dictdal.py", line 205, in assembly_instrument
    return assembly_instrument(self.components, keyval, date, by_key=by_key)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/instrument/assembly.py", line 220, in assembly_instrument
    return assembly_element(comp_store, 'instrument', keyval, date, by_key=by_key)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/instrument/assembly.py", line 245, in assembly_element
    somed = find_element(comp_store, etype, tmpl, date, by_key=by_key)
  File "/home/youdong/Software/anaconda2/envs/emir/lib/python3.10/site-packages/numina/instrument/assembly.py", line 197, in find_element
    raise ValueError(
ValueError: Not found instrument name=None for date=None

Not sure what is the problem, any one can help on it? Thanks a lot!

**Comment by sergiopasra** [comment]
Hello, this could happen for several different reasons.

Could you run:

```
numina show-instruments
```

and paste the result?

**Comment by PepeJoseHU** [comment]
Thanks Sergio,

Sorry, I forgot to keep the result this morning. And I reinstall version 0.20 and the error not appear with 'numina run dithered_ini.yaml --link-files -r control.yaml' . Because the dataset will need 7 hour to reduce once. So I think I will install 0.21 again with a small dataset to try it again.
For now it is:
INFO: Numina simple recipe runner version 0.32.3
LOAD
Instrument: EMIR
 version is '0.20'
 has configuration 'Default configuration' uuid=225fcaf2-7f6f-49cc-972a-70fd0aee8e96
 has datamodel 'emirdrp.datamodel.EmirDataModel'
 has pipeline 'default', version 1
Not sure if there have any problem on 0.20.
Do you have any idea with your experience?

Thank you very much!^_^
Best regards,
Youdong

________________________________
发件人: Sergio Pascual ***@***.***>
发送时间: 2024年10月3日 14:23
收件人: guaix-ucm/pyemir ***@***.***>
抄送: PepeJoseHU ***@***.***>; Author ***@***.***>
主题: Re: [guaix-ucm/pyemir] Problem after update to 0.21 version (Issue #148)


Hello, this could happen for several different reasons.

Could you run:

numina show-instruments


and paste the result?

―
