### ISSUE TITLE
Problem when combining many files

### ISSUE THREAD

**Issue by nicocardiel** [guaix-ucm/pyemir#151]
[dithered_v0_extreme.txt](https://github.com/user-attachments/files/17812548/dithered_v0_extreme.txt)
Using: `numina run dithered_v0_extreme.yaml --link-files -r control.yaml`with 112 images gives the following error:

```
INFO: storing task id=_combined_v0_extreme
Traceback (most recent call last):
  File "/Users/cardiel/venv_emir/bin/numina", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/cardiel/s/M1/numina/src/numina/user/cli.py", line 165, in main
    args.command(args, extra_args, config)
  File "/Users/cardiel/s/M1/numina/src/numina/user/clirun.py", line 123, in mode_run_obsmode
    mode_run_common(args, extra_args, config, mode='obs')
  File "/Users/cardiel/s/M1/numina/src/numina/user/clirundal.py", line 27, in mode_run_common
    return mode_run_common_obs(args, extra_args, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/numina/src/numina/user/clirundal.py", line 65, in mode_run_common_obs
    run_reduce(
  File "/Users/cardiel/s/M1/numina/src/numina/user/baserun.py", line 67, in run_reduce
    return run_task_reduce(task, datastore)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/numina/src/numina/user/baserun.py", line 174, in run_task_reduce
    completed_task = run_recipe_timed(task, recipe, rinput)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/numina/src/numina/user/baserun.py", line 187, in run_recipe_timed
    task.result = recipe(rinput)
                  ^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/numina/src/numina/core/recipes.py", line 155, in __call__
    result = self.run(recipe_input)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/pyemir/src/emirdrp/recipes/image/dither.py", line 275, in run
    result = self.process_basic(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/pyemir/src/emirdrp/recipes/image/dither.py", line 440, in process_basic
    result = self.combine_frames(target_info, extinction=extinction,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/s/M1/pyemir/src/emirdrp/recipes/image/dither.py", line 940, in combine_frames
    data = [i['primary'].data for i in frameslll]
            ^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/venv_emir/lib/python3.12/site-packages/astropy/utils/decorators.py", line 836, in __get__
    val = self.fget(obj)
          ^^^^^^^^^^^^^^
  File "/Users/cardiel/venv_emir/lib/python3.12/site-packages/astropy/io/fits/hdu/image.py", line 250, in data
    data = self._get_scaled_image_data(self._data_offset, self.shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/venv_emir/lib/python3.12/site-packages/astropy/io/fits/hdu/image.py", line 808, in _get_scaled_image_data
    raw_data = self._get_raw_data(shape, code, offset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/venv_emir/lib/python3.12/site-packages/astropy/io/fits/hdu/base.py", line 559, in _get_raw_data
    return self._file.readarray(offset=offset, dtype=code, shape=shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cardiel/venv_emir/lib/python3.12/site-packages/astropy/io/fits/file.py", line 364, in readarray
    self._mmap = mmap.mmap(
                 ^^^^^^^^^^
OSError: [Errno 24] Too many open files
```

**Comment by nicocardiel** [comment]
It turns out this is a limitation of the operating system. 

An easy way to solve it is to check the maximum number of allowed open files:

```
$ ulimit -Sn
```

You can easily increase this value using

```
$ ulimit -n <number>
```

where `<number>` is the required number.
