### ISSUE TITLE
When running dither + accumulate

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/pyemir#72]
INFO: Shape of resized array is [2399 2409]
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gtc/AL/OC/DF/DFBranch/ObservationSession.py", line 134, in reduceThread
    reductionResult = self._recipe.run(inputElement)
  File "/work/emir/lib/python/eggs/pyemir-0.9.dev1-py2.7.egg/emirdrp/decorators.py", line 60, in loginfo_method
    result = method(self, rinput)
  File "/work/emir/lib/python/eggs/pyemir-0.9.dev1-py2.7.egg/emirdrp/recipes/image/join.py", line 103, in run
    new_result = self.aggregate_result(partial_result, rinput)
  File "/work/emir/lib/python/eggs/pyemir-0.9.dev1-py2.7.egg/emirdrp/recipes/image/join.py", line 123, in aggregate_result
    newaccum = self.aggregate_frames(accum, frame, naccum)
  File "/work/emir/lib/python/eggs/pyemir-0.9.dev1-py2.7.egg/emirdrp/recipes/image/join.py", line 135, in aggregate_frames
    return self.aggregate2(accum, frame, naccum)
  File "/work/emir/lib/python/eggs/pyemir-0.9.dev1-py2.7.egg/emirdrp/recipes/image/join.py", line 377, in aggregate2
    fill=1
  File "/work/emir/lib/python/eggs/lib64/numina-0.15.dev0-py2.7-linux-x86_64.egg/numina/array/__init__.py", line 129, in resize_arrays
    fill=fill, scale=scale, conserve=conserve)
  File "/work/emir/lib/python/eggs/lib64/numina-0.15.dev0-py2.7-linux-x86_64.egg/numina/array/__init__.py", line 116, in resize_array
    newdata[region] = finaldata
ValueError: could not broadcast input array from shape (2396,2403) into shape (2396,2406)
Reduction thread stopped
Reduction thread stopped
Configuring STARE_IMAGE
Done

**Comment by sergiopasra** [comment]
This is a problem with the shapes of frame and accum, that are different in general and `self.compute_offset_wcs` fails
